### ISSUE TITLE
markdownの設定

### ISSUE THREAD

**Issue by kajikaji0725** [szpp-dev-team/szpp-judge-frontend#4]
- 問題文を書くのにmarkdownを使いたいから、vueにmarkdownを読み込める設定にしてほしい。

**Comment by h-takeyeah** [comment]
- ひとまず、問題文はすべてフロントエンド（ここ）が持っていて、バックエンドからは送られてこない想定です

**Comment by h-takeyeah** [comment]
これが使えそう https://github.com/antfu/vite-plugin-md

**Comment by h-takeyeah** [comment]
> これが使えそう https://github.com/antfu/vite-plugin-md

これはブラウザにコードを配信する前にviteでmdをhtmlに変換してやる試みであり、今回の用途とは違うので不採用になった

**Comment by h-takeyeah** [comment]
d85161c2a0bb6258e6c7eea4a4548820f782999f でパッケージを追加したので完了とする
